// styles/homeStyle.ts

import { StyleSheet } from 'react-native';

export const styles = {
  // Styles for Home Screen (Tổng quan)
  homeStyles: StyleSheet.create({
    scrollContainer: {
      flex: 1,
      backgroundColor: '#F4F7F9',
    },
    container: {
      paddingHorizontal: 20,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 30,
    },
    greeting: {
      fontSize: 26,
      fontWeight: '700',
      color: '#1F2937',
    },
    logoutButton: {
      padding: 5,
    },
    roleCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 15,
      marginBottom: 30,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 5,
    },
    roleInfo: {
      marginLeft: 15,
    },
    roleLabel: {
      fontSize: 14,
      color: '#6B7280',
      fontWeight: '500',
    },
    roleText: {
      fontSize: 22,
      fontWeight: '800',
      color: '#1F2937',
      marginTop: 2,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      marginBottom: 15,
    },
    statContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
    },
    statCard: {
      backgroundColor: '#FFFFFF',
      padding: 15,
      borderRadius: 10,
      width: '48%',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
      minHeight: 120,
      marginBottom: 15,
    },
    statNumber: {
      fontSize: 28,
      fontWeight: '800',
      color: '#1F2937',
      marginTop: 5,
    },
    statLabel: {
      fontSize: 14,
      color: '#6B7280',
      textAlign: 'center',
      marginTop: 5,
    },
    notificationCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      padding: 15,
      borderRadius: 10,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    notificationText: {
      marginLeft: 10,
      fontSize: 16,
      color: '#1F2937',
    },
    infoText: {
      fontSize: 16,
      color: '#6B7280',
      textAlign: 'center',
      paddingHorizontal: 10,
      lineHeight: 24,
    },
    loadingContainer: {
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
        color: '#6B7280',
    },
    errorContainer: {
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center',
        backgroundColor: '#FEE2E2',
        padding: 20,
    },
    errorText: {
        marginTop: 10,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#EF4444',
        textAlign: 'center',
    },
    tabBar: { 
        height: 60, 
        paddingBottom: 5, 
        paddingTop: 5 
    },
    tabBarLabel: {
        fontSize: 11,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 15,
      borderRadius: 10,
      marginTop: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      height: 50,
    },
    searchInput: {
      flex: 1,
      marginLeft: 10,
      fontSize: 16,
      color: '#1F2937',
    },
    modalPicker: {
      width: '100%',
      height: 50, // Đảm bảo chiều cao phù hợp
      color: '#1F2937',
    },
    modalLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
      marginBottom: 8,
      alignSelf: 'flex-start', // Căn chỉnh theo ý muốn
      marginTop: 10,
    },
  }),

  // Styles for Sales Screen (Quản lý Sản phẩm)
  salesStyles: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F3F4F6',
      paddingHorizontal: 20,
    },
    loadingContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#1F2937',
    },
    addButton: {
      padding: 5,
    },
    productList: {
      flex: 1,
    },
    productItem: {
      backgroundColor: '#FFFFFF',
      padding: 15,
      borderRadius: 12,
      marginBottom: 15,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    productInfo: {
      flex: 1,
    },
    productName: {
      fontSize: 18,
      fontWeight: '600',
      color: '#1F2937',
    },
    productDetails: {
      fontSize: 14,
      color: '#6B7280',
      marginTop: 5,
    },
    quantityControl: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    quantityText: {
      fontSize: 18,
      fontWeight: '600',
      color: '#374151',
      marginRight: 10,
    },
    quantityButtons: {
      flexDirection: 'row',
    },
    quantityButton: {
      padding: 5,
      marginLeft: 5,
    },
    emptyText: {
      textAlign: 'center',
      marginTop: 50,
      fontSize: 16,
      color: '#9CA3AF',
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalView: {
      width: '90%',
      backgroundColor: 'white',
      borderRadius: 20,
      padding: 35,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
      color: '#1F2937',
    },
    modalInput: {
      width: '100%',
      backgroundColor: '#F3F4F6',
      borderRadius: 8,
      padding: 10,
      marginBottom: 15,
      fontSize: 16,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '100%',
      marginTop: 20,
    },
    pickerContainer: {
      borderWidth: 1,
      borderColor: '#DDD',
      borderRadius: 8,
      marginBottom: 15,
      overflow: 'hidden', // Đảm bảo Picker không tràn ra ngoài
      backgroundColor: '#F3F4F6',
      height: 50, // Chiều cao cố định cho Picker
      justifyContent: 'center',
    },
    modalPicker: {
      width: '100%',
      height: 50, // Đảm bảo chiều cao phù hợp
      color: '#1F2937',
    },
  }),

  // Styles for Warehouse Screen (Quản lý Kho/Đơn hàng)
  warehouseStyles: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F3F4F6',
      paddingHorizontal: 20,
    },
    loadingContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#1F2937',
      marginBottom: 20,
    },
    orderList: {
      flex: 1,
    },
    orderItem: {
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 12,
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    orderHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    orderId: {
      fontSize: 18,
      fontWeight: '600',
      color: '#1F2937',
    },
    statusText: {
      fontSize: 16,
      fontWeight: '700',
    },
    orderInfo: {
      fontSize: 14,
      color: '#6B7280',
      marginBottom: 5,
    },
    itemsTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginTop: 10,
      marginBottom: 5,
    },
    itemDetail: {
      fontSize: 14,
      color: '#4B5563',
      marginLeft: 10,
    },
    actionButtons: {
      flexDirection: 'row',
      marginTop: 20,
      justifyContent: 'flex-end',
    },
    actionButton: {
      backgroundColor: '#10B981',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
    },
    actionButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
    },
    emptyText: {
      textAlign: 'center',
      marginTop: 50,
      fontSize: 16,
      color: '#9CA3AF',
    },
  }),

  // Styles for Staff Screen (Quản lý Nhân sự / Lịch làm)
  staffStyles: StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F3F4F6',
      paddingHorizontal: 20,
    },
    loadingContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollContainer: {
      flex: 1,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#1F2937',
      marginBottom: 20,
    },
    workHoursCard: {
      flexDirection: 'column',
      alignItems: 'flex-start',
      backgroundColor: '#FFFFFF',
      padding: 15,
      borderRadius: 12,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    workHoursText: {
      fontSize: 16,
      color: '#3B82F6',
      marginLeft: 10,
    },
    boldText: {
      fontWeight: 'bold',
      color: '#1F2937',
    },
    calendar: {
      marginBottom: 20,
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    scheduleDetailsCard: {
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    scheduleTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 10,
      color: '#1F2937',
    },
    detailText: {
      fontSize: 16,
      color: '#4B5563',
      marginBottom: 5,
    },
    noScheduleText: {
      fontSize: 16,
      color: '#9CA3AF',
      fontStyle: 'italic',
    },
    infoText: {
      fontSize: 16,
      color: '#6B7280',
      textAlign: 'center',
      lineHeight: 24,
    },
    list: {
      flex: 1,
    },
    staffItem: {
      backgroundColor: '#FFFFFF',
      padding: 15,
      borderRadius: 12,
      marginBottom: 15,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    staffInfo: {
      flex: 1,
    },
    staffName: {
      fontSize: 18,
      fontWeight: '600',
      color: '#1F2937',
    },
    staffRole: {
      fontSize: 14,
      color: '#6B7280',
      marginTop: 5,
    },
    staffHours: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#3B82F6',
      marginTop: 5,
    },
    actionButtons: {
      flexDirection: 'row',
    },
    buttonIcon: {
      marginLeft: 15,
    },
    infoCard: {
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    modalLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
      marginBottom: 8,
      alignSelf: 'flex-start', // Căn chỉnh theo ý muốn
      marginTop: 10,
    },
    checkInButton: {
      marginTop: 20,
      backgroundColor: '#10B981',
      paddingVertical: 12,
      paddingHorizontal: 30,
      borderRadius: 10,
      alignSelf: 'center', // Canh giữa nút
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
    },
    checkInButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    staffInfoCard: { // Renamed to avoid duplicate key
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 20,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  infoIcon: {
    marginRight: 15,
  },
  infoLabel: {
    fontSize: 16,
    color: '#374151',
    fontWeight: '600',
  },
  infoValue: {
    fontSize: 16,
    color: '#6B7280',
    marginLeft: 8,
    flex: 1, // Giúp text tự động xuống dòng nếu quá dài
    textAlign: 'right', // Căn phải cho đẹp
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    marginHorizontal: 20,
    marginTop: 30,
    paddingVertical: 15,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  editButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  }),

  // Styles for Chat Screen
  chatStyles: StyleSheet.create({
    listContainer: {
      flex: 1,
      backgroundColor: '#F7F8F9',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
      backgroundColor: '#fff',
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: '700',
      color: '#1F2937',
      marginLeft: 10,
    },
    chatItem: {
      flexDirection: 'row',
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
    },
    avatarContainer: {
      marginRight: 15,
      position: 'relative',
    },
    avatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: '#3B82F6',
      justifyContent: 'center',
      alignItems: 'center',
    },
    chatInfo: {
      flex: 1,
    },
    chatName: {
      fontSize: 18,
      fontWeight: '600',
      color: '#1F2937',
    },
    lastMessage: {
      fontSize: 14,
      color: '#6B7280',
      marginTop: 2,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    
    roomContainer: {
      flex: 1,
      backgroundColor: '#F7F8F9',
    },
    roomHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
      backgroundColor: '#fff',
    },
    roomTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1F2937',
      marginLeft: 10,
    },
    messageList: {
      flex: 1,
      paddingHorizontal: 10,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      borderTopWidth: 1,
      borderTopColor: '#E5E7EB',
      backgroundColor: '#fff',
    },
    textInput: {
      flex: 1,
      backgroundColor: '#F3F4F6',
      borderRadius: 20,
      paddingHorizontal: 15,
      paddingVertical: 10,
      maxHeight: 100,
      marginRight: 10,
    },
    sendButton: {
      backgroundColor: '#10B981',
      borderRadius: 20,
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    attachmentButton: {
      padding: 8,
      borderRadius: 20,
      marginRight: 5,
    },
    messageContainer: {
      marginVertical: 5,
      maxWidth: '80%',
    },
    myMessageContainer: {
      alignSelf: 'flex-end',
    },
    theirMessageContainer: {
      alignSelf: 'flex-start',
    },
    messageBubble: {
      padding: 10,
      borderRadius: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    myMessageBubble: {
      backgroundColor: '#10B981',
      borderBottomRightRadius: 0,
    },
    theirMessageBubble: {
      backgroundColor: '#FFFFFF',
      borderBottomLeftRadius: 0,
    },
    messageUser: {
      fontSize: 12,
      fontWeight: 'bold',
      marginBottom: 5,
    },
    messageText: {
      fontSize: 16,
    },
    messageTime: {
      fontSize: 10,
      alignSelf: 'flex-end',
      marginTop: 5,
    },
  }),
};